name: Update Memory File

on:
  schedule:
    - cron: '*/10 * * * *'  # Exécution toutes les 10 minutes (modifiable)
  workflow_dispatch: # Permet de l'exécuter manuellement

jobs:
  update-memory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Ajouter une mise à jour automatique
        run: |
          echo "\n---\n$(date) - Mise à jour automatique 🚀" >> Latest_memory.md
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add Latest_memory.md
          git commit -m "Mise à jour automatique"
          git push
